---
# tasks file for contoso_resource_group

- name: Create resource group if doesn't exist
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"
    state: present
  notify:
    - resource_group_created
